server:
  port: 8081
  servlet:
    context-path: /uaa

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uaa
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

jwt:
  signerKey: 1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij
  valid-duration: 15 #in second
  refreshable-duration: 6000 # in second

logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
